services:
  bitcoin:
    container_name: bitcoin
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    user: 33:33
    stop_grace_period: 70s
    stop_signal: SIGTERM
    image: farfoxachedocker/bitcoin:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config:/config:ro
      - /mnt/raid-pool/blockchains/Bitcoin:/bitcoin:rw
networks: {}
